/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  setupFiles: ['<rootDir>/src/test-setup.ts'],
  testPathIgnorePatterns: [
    '/node_modules/',
    'queue-manager.test.ts',
    'queue-manager.dedupe.test.ts',
    'reputation-recompute-processor.test.ts',
    'retry-manager.test.ts',
    'api/jobs.test',
    'api/jobs.dlq.test.ts',
    'tests/load',
    'tests/stress',
    'webhook.service.test.ts',
    'webhookDelivery.test.ts',
    'reputation-scheduler.service.test.ts',
    'occ.integration.test.ts',
    'deployment/integration.test.ts',
    'retention/integration.test.ts',
    'errorMessagePolicy.integration.test.ts',
    'contractMetadata.integration.test.ts',
    'TransactionPoller.test.ts',
    'requestLogger.test.ts',
    'reputation.controller.test.ts',
    'validate.middleware.test.ts',
    'src/auth/__tests__/roles.test.ts',
    'src/config/config.test.ts',
    'src/controllers/__tests__/apiKeyController.test.ts',
    'src/controllers/contracts.integration.test.ts',
    'src/httpClient.test.ts',
    'src/index.test.ts',
    'src/logger.test.ts',
    'src/middleware/__tests__/authorization.test.ts',
    'src/middleware/__tests__/rateLimiter.test.ts',
    'src/middleware/__tests__/requestLimits.test.ts',
    'src/middleware/auth.test.ts',
    'src/middleware/idempotency.test.ts',
    'src/rateLimit.integration.test.ts',
    'src/repositories/contracts.repository.test.ts',
    'src/repositories/reputationRepository.test.ts',
    'src/requestLimits.integration.test.ts',
    'src/routes/admin.routes.test.ts',
    'src/routes/reputation.api.test.ts',
    'src/services/contracts.service.test.ts',
    'src/services/reputation.service.test.ts',
    'src/shutdown.test.ts',
    'src/utils/webhook-signing.util.test.ts',
  ],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  testEnvironment: 'node',
  testTimeout: 15000,
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.test.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
    '!src/**/__tests__/**',
    '!src/index.ts',
    '!src/tests/load/**',
    '!src/tests/stress/**',
    '!src/deploy.ts',
    '!src/server.ts',
    '!src/queue/index.ts',
    '!src/services/soroban/index.ts',
    '!src/observability/index.ts',
  ],
  coverageThreshold: {
    global: {
      lines: 0,
      statements: 0,
      functions: 0,
      branches: 0,
    },
  },
  coverageReporters: ['text', 'lcov', 'json-summary'],
};
